- id: 1
  code: icbc
  currency: cny
  deposit: true
  withdraw: true
- id: 2
  code: cbc
  currency: cny
  deposit: true
  withdraw: true
- id: 3
  code: bc
  currency: cny
  deposit: true
  withdraw: true
- id: 4
  code: bcm
  currency: cny
  deposit: true
  withdraw: true
- id: 5
  code: abc
  currency: cny
  deposit: true
  withdraw: true
- id: 6
  code: cmb
  currency: cny
  deposit: true
  withdraw: true
- id: 7
  code: cmbc
  currency: cny
  deposit: true
  withdraw: true
- id: 8
  code: cncb
  currency: cny
  deposit: true
  withdraw: true
- id: 9
  code: hxb
  currency: cny
  deposit: true
  withdraw: true
- id: 10
  code: cib
  currency: cny
  deposit: true
  withdraw: true
- id: 11
  code: spdb
  currency: cny
  deposit: true
  withdraw: true
- id: 12
  code: bob
  currency: cny
  deposit: true
  withdraw: true
- id: 13
  code: ceb
  currency: cny
  deposit: true
  withdraw: true
- id: 14
  code: sdb
  currency: cny
  deposit: true
  withdraw: true
- id: 15
  code: pab
  currency: cny
  deposit: true
  withdraw: true
- id: 16
  code: gdb
  currency: cny
  deposit: true
  withdraw: true

# addnew new banks
- id: 17
  code: abgl
  currency: ghs
  deposit: true
  withdraw: true
- id: 18
  code: adbbl
  currency: ghs
  deposit: true
  withdraw: true
- id: 19
  code: bagl
  currency: ghs
  deposit: true
  withdraw: true
- id: 20
  code: bbgl
  currency: ghs
  deposit: true
  withdraw: true
- id: 21
  code: bsicgl
  currency: ghs
  deposit: true
  withdraw: true
- id: 22
  code: bbgl
  currency: ghs
  deposit: true
  withdraw: true
- id: 23
  code: calbl
  currency: ghs
  deposit: true
  withdraw: true
- id: 24
  code: egl
  currency: ghs
  deposit: true
  withdraw: true
- id: 25
  code: ebgl
  currency: ghs
  deposit: true
  withdraw: true
- id: 26
  code: fbnbgl
  currency: cny
  deposit: true
  withdraw: true
- id: 27
  code: fbgl
  currency: ghs
  deposit: true
  withdraw: true
- id: 28
  code: fabl
  currency: ghs
  deposit: true
  withdraw: true
- id: 29
  code: fnbgl
  currency: ghs
  deposit: true
  withdraw: true
- id: 30
  code: gcbbl
  currency: ghs
  deposit: true
  withdraw: true
- id: 31
  code: ghlbl
  currency: ghs
  deposit: true
  withdraw: true
- id: 32
  code: gnbl
  currency: ghs
  deposit: true
  withdraw: true
- id: 33
  code: gtbgl
  currency: ghs
  deposit: true
  withdraw: true
- id: 34
  code: hfcbgl
  currency: ghs
  deposit: true
  withdraw: true
- id: 35
  code: nibl
  currency: ghs
  deposit: true
  withdraw: true
- id: 36
  code: pbl
  currency: ghs
  deposit: true
  withdraw: true
- id: 37
  code: sggl
  currency: ghs
  deposit: true
  withdraw: true
- id: 38
  code: sbgl
  currency: ghs
  deposit: true
  withdraw: true
- id: 39
  code: scbgl
  currency: ghs
  deposit: true
  withdraw: true
- id: 40
  code: rbl
  currency: ghs
  deposit: true
  withdraw: true
- id: 41
  code: ugl
  currency: ghs
  deposit: true
  withdraw: true
- id: 42
  code: ubagl
  currency: ghs
  deposit: true
  withdraw: true
- id: 43
  code: umbgl
  currency: ghs
  deposit: true
  withdraw: true
- id: 44
  code: zbg
  currency: ghs
  deposit: true
  withdraw: true
- id: 45
  code: sbg
  currency: ghs
  deposit: true
  withdraw: true
- id: 46
  code: pbl
  currency: ghs
  deposit: true
  withdraw: true
- id: 47
  code: ogl
  currency: ghs
  deposit: true
  withdraw: true
- id: 48
  code: hbl
  currency: ghs
  deposit: true
  withdraw: true
- id: 49
  code: cbgl
  currency: ghs
  deposit: true
  withdraw: true
- id: 50
  code: bbl
  currency: ghs
  deposit: true
  withdraw: true
- id: 51
  code: arbabl
  currency: ghs
  deposit: true
  withdraw: true






