- id: 200
  key: bank
  currency: cny
  fixed: 2
  fee_max: 0
  min: 100
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
  type: WithdrawChannelBank

- id: 400
  key: naira
  currency: ngn
  fixed: 2
  fee_max: 0
  min: 100
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
  type: WithdrawChannelNaira

- id: 600
  key: dollar
  currency: usd
  fixed: 2
  fee_max: 0
  min: 10
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
  type: WithdrawChannelDollar

- id: 800
  key: euro
  currency: eur
  fixed: 2
  fee_max: 0
  min: 100
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
  type: WithdrawChannelEuro

- id: 1000
  key: pound
  currency: gbp
  fixed: 2
  fee_max: 0
  min: 10
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
  type: WithdrawChannelPound

- id: 1200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.0005
  inuse: true
  min: 100
  max: 50000
  type: WithdrawChannelSatoshi  

- id: 1600
  key: ghanaian
  currency: ghs
  fixed: 2
  fee: 0.0005
  inuse: true
  min: 100
  max: 50000
  type: WithdrawChannelGhanaian
  
